dependencies:
  - name: jupyterhub
    # Let's run as close to master as possible
    version: v0.9-445a953
    repository: https://jupyterhub.github.io/helm-chart
  - name: dask-gateway
    version: "0.6.1"
    repository: 'https://dask.org/dask-gateway-helm-repo/'
